global:
  scrape_interval: 1s
scrape_configs:
  - job_name: 'modbus'
    metrics_path: /modbus
    static_configs:
      - targets:
        - 127.0.0.1:1502  # Modbus device.
    params:
      module: ["fake"]
      sub_target: ["1"] # Modbus unit identifier, e.g. when using Modbus TCP as a gateway.
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9602  # The modbus exporter's real hostname:port.
